// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEtXqduMdfQjCoJwao5pXuHFh4a2rFOE0',
    appId: '1:364304254836:web:02ebb1735e3ab7c6880e21',
    messagingSenderId: '364304254836',
    projectId: 'owis-412911',
    authDomain: 'owis-412911.firebaseapp.com',
    databaseURL: 'https://owis-412911-default-rtdb.firebaseio.com',
    storageBucket: 'owis-412911.firebasestorage.app',
    measurementId: 'G-H1T76P7SYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlGFGgzsJiy-FhGM5Wtp8IDPRzGQHpCO0',
    appId: '1:364304254836:android:bffd9289c5ca501c880e21',
    messagingSenderId: '364304254836',
    projectId: 'owis-412911',
    databaseURL: 'https://owis-412911-default-rtdb.firebaseio.com',
    storageBucket: 'owis-412911.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX-m5pZzLA8SPXss18nxzODNDoe-TErlw',
    appId: '1:364304254836:ios:584dd23a1f89d09b880e21',
    messagingSenderId: '364304254836',
    projectId: 'owis-412911',
    databaseURL: 'https://owis-412911-default-rtdb.firebaseio.com',
    storageBucket: 'owis-412911.firebasestorage.app',
    iosBundleId: 'com.example.carServes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX-m5pZzLA8SPXss18nxzODNDoe-TErlw',
    appId: '1:364304254836:ios:584dd23a1f89d09b880e21',
    messagingSenderId: '364304254836',
    projectId: 'owis-412911',
    databaseURL: 'https://owis-412911-default-rtdb.firebaseio.com',
    storageBucket: 'owis-412911.firebasestorage.app',
    iosBundleId: 'com.example.carServes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEtXqduMdfQjCoJwao5pXuHFh4a2rFOE0',
    appId: '1:364304254836:web:0d55027a2ce5333c880e21',
    messagingSenderId: '364304254836',
    projectId: 'owis-412911',
    authDomain: 'owis-412911.firebaseapp.com',
    databaseURL: 'https://owis-412911-default-rtdb.firebaseio.com',
    storageBucket: 'owis-412911.firebasestorage.app',
    measurementId: 'G-58DWY5DFQ9',
  );

}